'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Final_Account_Defense_Barrier.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Arr_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arr_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Arr_Right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Arr_Right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property BIP39WORD() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("BIP39WORD", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_CSVEX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_CSVEX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_CSVEX_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_CSVEX_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_CSVIM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_CSVIM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_CSVIM_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_CSVIM_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_DEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_DEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_DEL_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_DEL_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_TRANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_TRANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_TRANS_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_TRANS_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CATMAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CATMAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_confirm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_confirm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_copy_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_copy_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_genpwd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_genpwd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_HELP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_HELP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_HKM_Title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_HKM_Title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_HKO_small_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_HKO_small_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_HKO_small_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_HKO_small_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_fileInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_fileInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveDWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveDWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_transKEY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_transKEY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Launch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Launch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_LOGOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_LOGOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_no() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_no", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_OpenF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_OpenF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_RESTART_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_RESTART_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_RESTART_On() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_RESTART_On", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_yes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_yes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property caps_lock_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caps_lock_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property caps_lock_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caps_lock_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CSV_EXP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CSV_EXP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CSV_IMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CSV_IMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property CSV_Waiting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CSV_Waiting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property EPTSLOT_313() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPTSLOT_313", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property EPTSLOT_692() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPTSLOT_692", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property exit_Pic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_Pic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property File_expo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("File_expo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_CRI_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_CRI_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_CRI_TXTB_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_CRI_TXTB_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_OK_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_OK_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_OK_TXTB_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_OK_TXTB_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_VRF_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_VRF_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_VRF_TXTB_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_VRF_TXTB_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property mit_Btn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mit_Btn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property MIT_DOC_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("MIT_DOC_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property mit_lic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mit_lic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD_HIDE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PASSWORD_HIDE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD_SHOW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PASSWORD_SHOW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PMP_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMP_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PMP_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PMP_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PWD_KDF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWD_KDF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PWD_KDF_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWD_KDF_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PWD_KDF_LINE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWD_KDF_LINE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PWD_KDF_PASS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWD_KDF_PASS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PWD_KDF_R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWD_KDF_R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property RUN_AS_ADMIN_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RUN_AS_ADMIN_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SALT_ADD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SALT_ADD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SALT_NO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SALT_NO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SCB_BAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCB_BAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SCB_BARV() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCB_BARV", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SCB_S_DW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCB_S_DW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SCB_S_UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCB_S_UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SECURE_DESKTOP_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SECURE_DESKTOP_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SETTINGS_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SETTINGS_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TimerID_ACT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerID_ACT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TimerID_INACT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerID_INACT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_LOGIN_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_LOGIN_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_NORMAL_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_NORMAL_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Byte[] 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_Password_PNG() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_Password_PNG", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TOPSEC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TOPSEC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property USING_SYMBOL_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USING_SYMBOL_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property USING_SYMBOL_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USING_SYMBOL_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property WinMin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WinMin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
