'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Final_Account_Defense_Barrier.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_DEL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_DEL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CAT_TRANS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CAT_TRANS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CATMAN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CATMAN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_CATMAN_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_CATMAN_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_confirm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_confirm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_confirm_dis() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_confirm_dis", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_COPY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_COPY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_copy_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_copy_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_genpwd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_genpwd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_HELP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_HELP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_delete_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_delete_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_fileInfo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_fileInfo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_fileInfo_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_fileInfo_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveDWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveDWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveDWN_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveDWN_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveUP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveUP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_moveUP_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_moveUP_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_save_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_save_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_transKEY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_transKEY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_L_transKEY_DI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_L_transKEY_DI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_Launch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_Launch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_LOGOUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_LOGOUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_OpenF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_OpenF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_RESTART_Off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_RESTART_Off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_RESTART_On() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_RESTART_On", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view_small() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view_small", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property button_view_small_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_view_small_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property caps_lock_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caps_lock_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property caps_lock_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caps_lock_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y__", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property DIGI_Y_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DIGI_Y_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property EPTSLOT_246() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPTSLOT_246", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property EPTSLOT_313() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPTSLOT_313", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property EPTSLOT_692() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EPTSLOT_692", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property File_expo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("File_expo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property main() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_CRI() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_CRI", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_CRI_TXTB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_CRI_TXTB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_OK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_OK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_OK_TXTB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_OK_TXTB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_VRF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_VRF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Message_VRF_TXTB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Message_VRF_TXTB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property mit_Btn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mit_Btn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property mit_lic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mit_lic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD_HIDE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PASSWORD_HIDE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property PASSWORD_SHOW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PASSWORD_SHOW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property RUN_AS_ADMIN_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RUN_AS_ADMIN_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property RUN_AS_ADMIN_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RUN_AS_ADMIN_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property salting_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salting_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SECURE_DESKTOP_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SECURE_DESKTOP_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property SECURE_DESKTOP_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SECURE_DESKTOP_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TimerID_ACT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerID_ACT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TimerID_INACT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TimerID_INACT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_LOGIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_LOGIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_NORMAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_NORMAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property Title_Password() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Title_Password", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property TOPSEC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TOPSEC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property USING_SYMBOL_OFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USING_SYMBOL_OFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend Shared ReadOnly Property USING_SYMBOL_ON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("USING_SYMBOL_ON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
